/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.DeliveryManRole;

import Business.Employee.Employee;
import Business.DeliveryMan.DeliveryMan;
import Business.DeliveryMan.DeliveryManDirectory;
import Business.EcoSystem;
import Business.Role.DeliverManRole;
import java.awt.CardLayout;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author namangupta
 */
public class AddDeliverManJPanel extends javax.swing.JPanel {

    /**
     * Creates new form AddDeliverManJPanel
     */
    
    EcoSystem ecosystem;
    DeliveryManDirectory deliveryManDirectory;
    JPanel userProcessContainer;
    
    public AddDeliverManJPanel(JPanel userProcessContainer, EcoSystem ecosystem, DeliveryManDirectory deliveryManDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.deliveryManDirectory = deliveryManDirectory;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblAddCustomer = new javax.swing.JLabel();
        lblDeliveryManName = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        lblDeliveryVehicle = new javax.swing.JLabel();
        txtVehicleNumber = new javax.swing.JTextField();
        lblDeliveryManContact = new javax.swing.JLabel();
        txtContact = new javax.swing.JTextField();
        lblDeliveryEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAddDeliveryMan = new javax.swing.JButton();
        lblNameError = new javax.swing.JLabel();
        lblVehicleError = new javax.swing.JLabel();
        lblContactError = new javax.swing.JLabel();
        lblEmailError = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                formKeyReleased(evt);
            }
        });

        lblAddCustomer.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblAddCustomer.setText("ADD DELIVERY MAN");

        lblDeliveryManName.setText("NAME:");

        txtName.setBackground(new java.awt.Color(255, 255, 204));
        txtName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtNameKeyReleased(evt);
            }
        });

        lblDeliveryVehicle.setText("VEHICLE NUMBER");

        txtVehicleNumber.setBackground(new java.awt.Color(255, 255, 204));

        lblDeliveryManContact.setText("CONTACT NUMBER:");

        txtContact.setBackground(new java.awt.Color(255, 255, 204));
        txtContact.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtContactKeyReleased(evt);
            }
        });

        lblDeliveryEmail.setText("EMAIL ID:");

        txtEmail.setBackground(new java.awt.Color(255, 255, 204));
        txtEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmailActionPerformed(evt);
            }
        });

        btnAddDeliveryMan.setBackground(new java.awt.Color(255, 255, 204));
        btnAddDeliveryMan.setText("ADD");
        btnAddDeliveryMan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDeliveryManActionPerformed(evt);
            }
        });

        lblNameError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblNameErrorKeyReleased(evt);
            }
        });

        lblContactError.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblContactErrorKeyReleased(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblPassword.setText("PASSWORD:");

        txtPassword.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(346, 346, 346)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblPassword)
                                    .addComponent(lblDeliveryManName)
                                    .addComponent(lblDeliveryVehicle)
                                    .addComponent(lblDeliveryManContact)
                                    .addComponent(lblDeliveryEmail))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtName, javax.swing.GroupLayout.DEFAULT_SIZE, 86, Short.MAX_VALUE)
                                        .addComponent(txtVehicleNumber, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtPassword))
                                .addGap(54, 54, 54)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblVehicleError)
                                    .addComponent(lblContactError)
                                    .addComponent(lblEmailError)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(btnAddDeliveryMan, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(btnBack)
                        .addGap(270, 270, 270)
                        .addComponent(lblAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtContact, txtEmail, txtName, txtPassword, txtVehicleNumber});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(btnBack))
                    .addComponent(lblAddCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryManName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNameError, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryVehicle)
                    .addComponent(txtVehicleNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblVehicleError))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryManContact)
                    .addComponent(txtContact, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblContactError))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDeliveryEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblEmailError))
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddDeliveryMan)
                .addGap(360, 360, 360))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmailActionPerformed

    private void btnAddDeliveryManActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDeliveryManActionPerformed
        // TODO add your handling code here:
        if(checkFormValidity()){
        Employee employee = this.ecosystem.getEmployeeDirectory().createEmployee("RRH");

        DeliveryMan deliveryMan = new DeliveryMan();
        deliveryMan.setName(txtName.getText());
        deliveryMan.setVehicleNumber(txtVehicleNumber.getText());
        deliveryMan.setContactNumber(Long.parseLong(txtContact.getText()));
        deliveryMan.setEmail(txtEmail.getText());
        deliveryMan.setPassword(txtPassword.getText());

        deliveryManDirectory.addDeliveryMan(deliveryMan);

        this.ecosystem.setDeliveryManDirectory(deliveryManDirectory);
        this.ecosystem.getUserAccountDirectory().createUserAccount(txtEmail.getText(), txtPassword.getText(), employee, new DeliverManRole());
        JOptionPane.showMessageDialog(this, "Delivery Man Added", "Update", JOptionPane.INFORMATION_MESSAGE);
        clearFields();
        }
        else{
            JOptionPane.showMessageDialog(this, "Please resolve all errors and fill all the fields", "Error", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnAddDeliveryManActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:

        SystemAdminWorkAreaJPanel back = new SystemAdminWorkAreaJPanel(userProcessContainer, this.ecosystem);

        userProcessContainer.add("WorkAreaJPanel", back);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void lblNameErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblNameErrorKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lblNameErrorKeyReleased

    private void lblContactErrorKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblContactErrorKeyReleased
        // TODO add your handling code here:

    }//GEN-LAST:event_lblContactErrorKeyReleased

    private void formKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_formKeyReleased

    private void txtNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNameKeyReleased
        // TODO add your handling code here:
        Pattern patt=Pattern.compile("^[a-zA-Z ]{0,40}$");
        Matcher match=patt.matcher(txtName.getText());
        if (!match.matches()) {
            lblNameError.setText("You can only use alphabets(a-z) and maximum length is 40");
        }else{
            lblNameError.setText("");
        }
    }//GEN-LAST:event_txtNameKeyReleased

    private void txtContactKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtContactKeyReleased
        // TODO add your handling code here:
        Pattern patt=Pattern.compile("^[0-9]{10}{12}$");
        Matcher match=patt.matcher(txtContact.getText());
        if (!match.matches()) {
            lblContactError.setText("Number should be 10 digits");
        }else{
            lblContactError.setText("");
        }
    }//GEN-LAST:event_txtContactKeyReleased

    public void clearFields(){
        txtName.setText("");
        txtVehicleNumber.setText("");
        txtContact.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
    }
    
    private Boolean checkFormValidity(){
        if(txtVehicleNumber.getText().length() != 0 && txtContact.getText().length() != 0 && txtEmail.getText().length() != 0 
                && txtName.getText().length() != 0 && txtPassword.getText().length() != 0 && lblNameError.getText().length() == 0
                && lblContactError.getText().length() == 0){
            return true;
        }
        else{
            return false;
        }
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDeliveryMan;
    private javax.swing.JButton btnBack;
    private javax.swing.JLabel lblAddCustomer;
    private javax.swing.JLabel lblContactError;
    private javax.swing.JLabel lblDeliveryEmail;
    private javax.swing.JLabel lblDeliveryManContact;
    private javax.swing.JLabel lblDeliveryManName;
    private javax.swing.JLabel lblDeliveryVehicle;
    private javax.swing.JLabel lblEmailError;
    private javax.swing.JLabel lblNameError;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblVehicleError;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    private javax.swing.JTextField txtVehicleNumber;
    // End of variables declaration//GEN-END:variables
}
