/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package userinterface.RestaurantAdminRole;

import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Restaurant.Restaurant;
import Business.Restaurant.RestaurantDirectory;
import Business.Role.AdminRole;
import java.awt.CardLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import userinterface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;

/**
 *
 * @author namangupta
 */
public class ManageRestaurantJPanel extends javax.swing.JPanel {

    /**
     * Creates new form ManageRestaurantJPanel
     */
    
    JPanel userProcessContainer;
    EcoSystem ecosystem;
    RestaurantDirectory restaurantDirectory;
    
    public ManageRestaurantJPanel(JPanel userProcessContainer, EcoSystem ecosystem, RestaurantDirectory restaurantDirectory) {
        this.userProcessContainer = userProcessContainer;
        this.ecosystem = ecosystem;
        this.restaurantDirectory = restaurantDirectory;
        initComponents();
        populateRestaurantTable(this.restaurantDirectory);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblRestaurant = new javax.swing.JTable();
        btnUpdateCustomer = new javax.swing.JButton();
        btnDeleteRestaurant = new javax.swing.JButton();
        lblUpdateRestaurant = new javax.swing.JLabel();
        lblName = new javax.swing.JLabel();
        lblAddress = new javax.swing.JLabel();
        lblContact = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        txtAddress = new javax.swing.JTextField();
        txtContact = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnBack = new javax.swing.JButton();
        btnViewRestaurant = new javax.swing.JButton();
        lblPassword = new javax.swing.JLabel();
        txtPassword = new javax.swing.JTextField();

        setBackground(new java.awt.Color(204, 255, 204));

        lblTitle.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblTitle.setText("MANAGE RESTAURANT");

        tblRestaurant.setBackground(new java.awt.Color(255, 255, 204));
        tblRestaurant.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "NAME", "ADDRESS", "CONTACT", "EMAIL", "PASSWORD"
            }
        ));
        jScrollPane1.setViewportView(tblRestaurant);

        btnUpdateCustomer.setBackground(new java.awt.Color(255, 255, 204));
        btnUpdateCustomer.setText("Update Customer");
        btnUpdateCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateCustomerActionPerformed(evt);
            }
        });

        btnDeleteRestaurant.setBackground(new java.awt.Color(255, 255, 204));
        btnDeleteRestaurant.setText("Delete Restaurant");
        btnDeleteRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteRestaurantActionPerformed(evt);
            }
        });

        lblUpdateRestaurant.setFont(new java.awt.Font("Lucida Grande", 1, 18)); // NOI18N
        lblUpdateRestaurant.setText("UPDATE RESTAURANT");

        lblName.setText("NAME:");

        lblAddress.setText("ADDRESS:");

        lblContact.setText("CONTACT:");

        lblEmail.setText("EMAIL:");

        txtName.setBackground(new java.awt.Color(255, 255, 204));

        txtAddress.setBackground(new java.awt.Color(255, 255, 204));

        txtContact.setBackground(new java.awt.Color(255, 255, 204));

        txtEmail.setBackground(new java.awt.Color(255, 255, 204));

        btnBack.setBackground(new java.awt.Color(255, 255, 204));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        btnViewRestaurant.setBackground(new java.awt.Color(255, 255, 204));
        btnViewRestaurant.setText("View Restaurant");
        btnViewRestaurant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewRestaurantActionPerformed(evt);
            }
        });

        lblPassword.setText("PASSWORD:");

        txtPassword.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblPassword)
                .addGap(486, 486, 486))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(398, 398, 398)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail)
                            .addComponent(btnUpdateCustomer)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(373, 373, 373)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblContact, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblAddress, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblName, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(37, 37, 37)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(txtContact)
                                        .addComponent(txtEmail)
                                        .addComponent(txtPassword)
                                        .addComponent(txtAddress))
                                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(5, 5, 5)
                                .addComponent(lblUpdateRestaurant))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBack)
                                .addGap(239, 239, 239)
                                .addComponent(lblTitle))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnDeleteRestaurant)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnViewRestaurant))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(42, 42, 42))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {txtAddress, txtContact, txtEmail, txtName, txtPassword});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTitle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBack))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 206, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnDeleteRestaurant)
                    .addComponent(btnViewRestaurant))
                .addGap(8, 8, 8)
                .addComponent(lblUpdateRestaurant)
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblName)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAddress)
                    .addComponent(txtAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblContact, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtContact, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmail)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPassword)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addComponent(btnUpdateCustomer)
                .addGap(48, 48, 48))
        );
    }// </editor-fold>//GEN-END:initComponents

    
    private void populateRestaurantTable(RestaurantDirectory restaurantList) {
        DefaultTableModel model = (DefaultTableModel) tblRestaurant.getModel();
        model.setRowCount(0);
        if(restaurantList.getRestaurantDirectory().isEmpty())
        {
            JOptionPane.showMessageDialog(this, "No Customer Please add"
                    + "Customer", "Warning", JOptionPane.INFORMATION_MESSAGE);
            return;
        }
        for (Restaurant restaurant : restaurantList.getRestaurantDirectory()) {
            Object[] row = new Object[5];
            row[0] = restaurant;
            row[1] = restaurant.getAddress();
            row[2] = restaurant.getContact();
            row[3] = restaurant.getEmail();
            row[4] = restaurant.getPassword();
            model.addRow(row);
        }
    }
    
    private void btnUpdateCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateCustomerActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblRestaurant.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblRestaurant.getModel();
        Restaurant selectedRestaurant = (Restaurant) model.getValueAt(selectedRowIndex, 0);

        restaurantDirectory.deleteRestaurant(selectedRestaurant);
        Restaurant restaurant = new Restaurant();
        restaurant.setName(txtName.getText());
        restaurant.setAddress(txtAddress.getText());
        restaurant.setContact(Long.parseLong(txtContact.getText()));
        restaurant.setEmail(txtEmail.getText());
        restaurant.setPassword(txtPassword.getText());

        restaurantDirectory.addRestaurant(restaurant);
        this.ecosystem.setRestaurantDirectory(restaurantDirectory);

        Employee employee = this.ecosystem.getEmployeeDirectory().createEmployee("RRH");
        this.ecosystem.getUserAccountDirectory().createUserAccount(txtEmail.getText(), txtPassword.getText(), employee, new AdminRole());

        JOptionPane.showMessageDialog(this, "Restaurant Updated", "Update", JOptionPane.INFORMATION_MESSAGE);
        clearFields();
        
        populateRestaurantTable(this.ecosystem.getRestaurantDirectory());
    }//GEN-LAST:event_btnUpdateCustomerActionPerformed

    private void btnDeleteRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteRestaurantActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblRestaurant.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblRestaurant.getModel();
        Restaurant selectedRestaurant = (Restaurant) model.getValueAt(selectedRowIndex, 0);

        restaurantDirectory.deleteRestaurant(selectedRestaurant);
        this.ecosystem.setRestaurantDirectory(restaurantDirectory);
        JOptionPane.showMessageDialog(this, "Selected Customer Deleted.");
        populateRestaurantTable(this.ecosystem.getRestaurantDirectory());
    }//GEN-LAST:event_btnDeleteRestaurantActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        SystemAdminWorkAreaJPanel back = new SystemAdminWorkAreaJPanel(userProcessContainer, this.ecosystem);

        userProcessContainer.add("WorkAreaJPanel", back);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnViewRestaurantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewRestaurantActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblRestaurant.getSelectedRow();

        if(selectedRowIndex < 0){
            JOptionPane.showMessageDialog(this, "Please select a row to delete.");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblRestaurant.getModel();
        Restaurant selectedRestaurant = (Restaurant) model.getValueAt(selectedRowIndex, 0);

        txtName.setText(selectedRestaurant.getName());
        txtAddress.setText(selectedRestaurant.getAddress());
        txtContact.setText(String.valueOf(selectedRestaurant.getContact()));
        txtEmail.setText(selectedRestaurant.getEmail());
        txtPassword.setText(selectedRestaurant.getPassword());
    }//GEN-LAST:event_btnViewRestaurantActionPerformed

    public void clearFields(){
        txtName.setText("");
        txtAddress.setText("");
        txtContact.setText("");
        txtEmail.setText("");
        txtPassword.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnDeleteRestaurant;
    private javax.swing.JButton btnUpdateCustomer;
    private javax.swing.JButton btnViewRestaurant;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAddress;
    private javax.swing.JLabel lblContact;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lblUpdateRestaurant;
    private javax.swing.JTable tblRestaurant;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtContact;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtPassword;
    // End of variables declaration//GEN-END:variables
}
